version: '3'

volumes:
  studentiunimi_backend_postgres:
    external: true
  static_files:

networks:
  db_net:
  django_net:
  nginx_net:
    external: true

services:
  postgres:
    image: postgres
    container_name: studentiunimi_backend_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    volumes:
      - studentiunimi_backend_postgres:/var/lib/postgresql/data
    networks:
      - db_net

  django:
    image: ghcr.io/studentiunimi/backend:latest
    container_name: studentiunimi_backend_django
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - static_files:/usr/src/app/static/
    depends_on:
      - postgres
    networks:
      - db_net
      - django_net

  nginx:
    image: nginx:latest
    container_name: studentiunimi_backend_nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - static_files:/static
    networks:
      - django_net
      - nginx_net
    depends_on:
      - django
