version: '3'

volumes:
  studunimi-backend_postgres:
    external: true
  studunimi-backend_userbot-sessions:
    external: true
  static_files:

networks:
  db_net:
  django_net:
  traefik_net:
    external: true

services:
  postgres:
    image: postgres:12
    container_name: studentiunimi_backend_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    volumes:
      - studunimi-backend_postgres:/var/lib/postgresql/data
    networks:
      - db_net
    deploy:
      replicas: 1

  django:
    image: ghcr.io/studentiunimi/backend:latest
    container_name: studentiunimi_backend_django
    environment:
      - SERVER_NAME=${SERVER_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      - SECRET_KEY=${SECRET_KEY}
      - LOGGING_CHAT_ID=${LOGGING_CHAT_ID}
      - LOGGING_BOT_TOKEN=${LOGGING_BOT_TOKEN}
      - TELEGRAM_API_ID=${TELEGRAM_API_ID}
      - TELEGRAM_API_HASH=${TELEGRAM_API_HASH}
      - SENTRY_DSN=${SENTRY_DSN}
      - TELEGRAM_ADMIN_GROUP_ID=${TELEGRAM_ADMIN_GROUP_ID}
    volumes:
      - static_files:/usr/src/app/static/
      - studunimi-backend_userbot-sessions:/usr/src/app/media/userbot-sessions
    depends_on:
      - postgres
    networks:
      - db_net
      - django_net

  nginx:
    image: nginx:latest
    container_name: studentiunimi_backend_nginx
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - static_files:/static
    networks:
      - django_net
      - traefik_net
    depends_on:
      - django
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.studunimi-backend.loadbalancer.server.port=8000"
