version: '3'

volumes:
  studentiunimi_backend_postgres:
    external: true

networks:
  db_net:
  nginx_net:
    external: true

services:
  postgres:
    image: postgres
    container_name: studentiunimi_backend_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    volumes:
      - studentiunimi_backend_postgres:/var/lib/postgresql/data
    networks:
      - db_net

  django:
    build: .
    container_name: studentiunimi_backend_django
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      - postgres
    networks:
      - db_net
      - nginx_net
