version: '3'

volumes:
  studentiunimi_backend_postgres:
    external: true

services:
  postgres:
    image: postgres
    container_name: studentiunimi_backend_postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DBNAME}
    volumes:
      - studentiunimi_backend_postgres:/var/lib/postgresql/data

  django:
    build: .
    container_name: studentiunimi_backend_django
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DBNAME=${POSTGRES_DBNAME}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - 8000:8000
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
