# Generated by Django 3.2.5 on 2021-07-26 12:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='last_seen',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='last seen'),
        ),
        migrations.AddField(
            model_name='groupmembership',
            name='messages_count',
            field=models.PositiveIntegerField(default=0, verbose_name='messages count'),
        ),
    ]
