# Generated by Django 3.2.5 on 2021-08-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0003_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBot',
            fields=[
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='token')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'Telegram bot',
                'verbose_name_plural': 'Telegram bots',
            },
        ),
    ]
