# Generated by Django 3.2.5 on 2021-08-09 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0005_userprivilege'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='bot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='telegrambot.telegrambot'),
        ),
    ]
