# Generated by Django 3.2.5 on 2021-08-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0006_group_bot'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='welcome_model',
            field=models.TextField(default='<b>{greetings}</b> nel gruppo {title}\n\nIscriviti al canale @studenti_unimi', help_text='Available format parameters: {greetings} and {title}', verbose_name='Welcome model'),
        ),
    ]
