# Generated by Django 3.2.5 on 2021-08-13 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0007_group_welcome_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrambot',
            name='username',
            field=models.CharField(blank=True, max_length=32, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='group',
            name='bot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='telegrambot.telegrambot'),
        ),
    ]
