# Generated by Django 3.2.5 on 2021-08-13 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0008_auto_20210813_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmembership',
            name='status',
            field=models.CharField(choices=[('creator', 'Creator'), ('administrator', 'Administrator'), ('member', 'Member'), ('restricted', 'Restricted'), ('left', 'Left'), ('kicked', 'Kicked')], default='member', max_length=16, verbose_name='status'),
        ),
    ]
