# Generated by Django 3.2.6 on 2021-09-04 15:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0010_userprivilege_can_superban_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUserbot',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='telegrambot.user')),
                ('active', models.BooleanField(default=False, verbose_name='active')),
                ('group_count', models.IntegerField(default=0, verbose_name='group count')),
                ('last_used', models.DateTimeField(default=datetime.datetime.now, verbose_name='last used')),
            ],
            options={
                'verbose_name': 'Telegram userbot',
                'verbose_name_plural': 'Telegram userbots',
            },
        ),
    ]
