# Generated by Django 3.2.9 on 2021-11-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0012_telegramuserbot_session_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.BigIntegerField(help_text='Set the ID to 0 if you want an userbot to actually create the group', primary_key=True, serialize=False, unique=True, verbose_name='Telegram group ID'),
        ),
        migrations.AlterField(
            model_name='telegramuserbot',
            name='session_file',
            field=models.FileField(upload_to='userbot-sessions/', verbose_name='telethon session file'),
        ),
    ]
