# Generated by Django 3.2.9 on 2021-11-16 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0013_auto_20211107_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='ignore_admin_tagging',
            field=models.BooleanField(default=False, verbose_name='Ignore @admin tagging'),
        ),
    ]
