# Generated by Django 3.2.9 on 2021-11-18 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0014_group_ignore_admin_tagging'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotWhitelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, unique=True, verbose_name='username')),
                ('whitelisted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegrambot.user')),
            ],
            options={
                'verbose_name': "Whitelist'd bot",
                'verbose_name_plural': "Whitelist'd bots",
            },
        ),
    ]
