# Generated by Django 3.2.9 on 2022-02-24 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0011_alter_representative_degree_name'),
        ('telegrambot', '0015_botwhitelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='degree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='university.degree'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('IT', 'Italian'), ('EN', 'English')], default='IT', max_length=2, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='user',
            name='rules_accepted',
            field=models.BooleanField(default=False, verbose_name='has accepted rules?'),
        ),
    ]
