# Generated by Django 3.2.9 on 2022-04-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0017_alter_userprivilege_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedUser',
            fields=[
                ('user_id', models.PositiveBigIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Telegram user ID')),
                ('source', models.CharField(choices=[('A', 'Administrator'), ('GH', 'GroupHelp')], max_length=2, verbose_name='source')),
            ],
            options={
                'verbose_name': 'Blacklisted user',
                'verbose_name_plural': 'Blacklisted users',
            },
        ),
        migrations.AlterModelOptions(
            name='botwhitelist',
            options={'verbose_name': 'Whitelisted bot', 'verbose_name_plural': 'Whitelisted bots'},
        ),
    ]
