# Generated by Django 3.2.9 on 2022-04-15 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0018_auto_20220415_1100'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('user', 'group')},
        ),
    ]
