# Generated by Django 3.2.9 on 2022-04-17 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0019_alter_groupmembership_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramlog',
            name='message_deleted',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
