# Generated by Django 3.2.9 on 2022-06-22 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0020_telegramlog_message_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='language',
            field=models.CharField(blank=True, default='it', max_length=3, null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='language'),
        ),
    ]
