# Generated by Django 3.2.9 on 2022-07-02 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0022_auto_20220702_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='welcome_model',
            field=models.TextField(blank=True, help_text='Available format parameters: {greetings} and {title}', null=True, verbose_name='Welcome model'),
        ),
        migrations.AlterField(
            model_name='group',
            name='welcome_model_en',
            field=models.TextField(blank=True, help_text='Available format parameters: {greetings} and {title}', null=True, verbose_name='Welcome model'),
        ),
        migrations.AlterField(
            model_name='group',
            name='welcome_model_it',
            field=models.TextField(blank=True, help_text='Available format parameters: {greetings} and {title}', null=True, verbose_name='Welcome model'),
        ),
    ]
