# Generated by Django 3.2.9 on 2022-09-26 15:35

from django.db import migrations, models


with open("telegrambot/migrations/0024_auto_20220926_1535.sql") as f:
    lines = f.readlines()

sql = ' '.join(filter(lambda l: len(l) > 1 and not l.startswith('--'), ''.join(lines).split('\n')))

class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0023_auto_20220702_2346'),
    ]

    operations = [
        migrations.RunSQL(
            sql=sql,
            state_operations=[
                migrations.AddField(
                    model_name='telegrambot',
                    name='id',
                    field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
                    preserve_default=False,
                ),
                migrations.AlterField(
                    model_name='telegrambot',
                    name='token',
                    field=models.CharField(max_length=64, verbose_name='token'),
                ),
            ]
        ),
    ]
