# Generated by Django 3.2.9 on 2022-09-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0024_auto_20220926_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegrambot',
            name='token',
            field=models.CharField(max_length=64, unique=True, verbose_name='token'),
        ),
    ]
