# Generated by Django 3.2.9 on 2022-10-08 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0025_alter_telegrambot_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The regex will use a fullmatch', max_length=500, unique=True, verbose_name='Regex')),
                ('delete', models.BooleanField(help_text='Delete the message that matched the regex', verbose_name='Delete message')),
                ('notify', models.BooleanField(help_text='Notify admins that a message matched the regex', verbose_name='Notify admins')),
                ('reply', models.BooleanField(help_text='Send the message specified in the message field in the chatof the message that matched the regex', verbose_name='Reply in chat')),
                ('message', models.TextField(blank=True, null=True)),
                ('moderation', models.IntegerField(choices=[(1, 'NOTHING'), (2, 'MODERATION_INFO'), (3, 'MODERATION_WARN'), (4, 'MODERATION_KICK'), (5, 'MODERATION_BAN'), (6, 'MODERATION_MUTE'), (7, 'MODERATION_FREE'), (8, 'MODERATION_SUPERBAN'), (9, 'MODERATION_SUPERFREE')], null=True)),
            ],
            options={
                'verbose_name': 'Message filter',
                'verbose_name_plural': 'Message filters',
            },
        ),
    ]
