# Generated by Django 3.2.9 on 2022-09-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0025_alter_telegrambot_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500, unique=True, verbose_name='Regex')),
            ],
            options={
                'verbose_name': 'Message filter',
                'verbose_name_plural': 'Message filters',
            },
        ),
    ]
