# Generated by Django 3.2.9 on 2023-10-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0026_auto_20230815_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='extra_group_category',
        ),
        migrations.RemoveField(
            model_name='group',
            name='extra_group_description',
        ),
        migrations.RemoveField(
            model_name='group',
            name='extra_group_description_en',
        ),
        migrations.RemoveField(
            model_name='group',
            name='extra_group_description_it',
        ),
        migrations.RemoveField(
            model_name='group',
            name='extra_group_name',
        ),
        migrations.RemoveField(
            model_name='group',
            name='extra_group_name_en',
        ),
        migrations.RemoveField(
            model_name='group',
            name='extra_group_name_it',
        ),
    ]
