# Generated by Django 3.2.9 on 2022-03-26 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('university', '0011_alter_representative_degree_name'),
        ('telegrambot', '0016_telegramlog'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('all_groups', models.BooleanField(default=False, verbose_name='All groups')),
                ('moderation_info', models.BooleanField(blank=True, default=None, help_text='/info command', null=True)),
                ('moderation_del', models.BooleanField(blank=True, default=None, help_text='/del command', null=True)),
                ('moderation_warn', models.BooleanField(blank=True, default=None, help_text='/warn command', null=True)),
                ('moderation_kick', models.BooleanField(blank=True, default=None, help_text='/kick command', null=True)),
                ('moderation_ban', models.BooleanField(blank=True, default=None, help_text='/ban command', null=True)),
                ('moderation_mute', models.BooleanField(blank=True, default=None, help_text='/mute command', null=True)),
                ('moderation_free', models.BooleanField(blank=True, default=None, help_text='/free command', null=True)),
                ('moderation_superban', models.BooleanField(blank=True, default=None, help_text='/superban command', null=True)),
                ('moderation_superfree', models.BooleanField(blank=True, default=None, help_text='/superfree command', null=True)),
                ('can_change_info', models.BooleanField(blank=True, default=None, help_text='True, if the user is allowed to change the chat title, photo and other settings', null=True)),
                ('can_invite_users', models.BooleanField(blank=True, default=None, help_text='True, if the user is allowed to invite new users to the chat', null=True)),
                ('can_pin_messages', models.BooleanField(blank=True, default=None, help_text='True, if the user is allowed to pin messages; groups and supergroups only', null=True)),
                ('can_manage_chat', models.BooleanField(blank=True, default=None, help_text='True, if the administrator can access the chat event log, chat statistics, message statistics in channels, see channel members, see anonymous administrators in supergroups and ignore slow mode. Implied by any other administrator privilege', null=True)),
                ('can_delete_messages', models.BooleanField(blank=True, default=None, help_text='True, if the administrator can delete messages of other users', null=True)),
                ('can_manage_voice_chats', models.BooleanField(blank=True, default=None, help_text='True, if the administrator can manage voice chats', null=True)),
                ('can_restrict_members', models.BooleanField(blank=True, default=None, help_text='True, if the administrator can restrict, ban or unban chat members', null=True)),
                ('can_promote_members', models.BooleanField(blank=True, default=None, help_text='True, if the administrator can add new administrators with a subset of their own privileges or demote administrators that he has promoted, directly or indirectly (promoted by administrators that were appointed by the user)', null=True)),
                ('degrees', models.ManyToManyField(related_name='roles', to='university.Degree')),
                ('django_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_roles.baserole_set+', to='contenttypes.contenttype')),
                ('tg_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegrambot.user')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('baserole_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='roles.baserole')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('roles.baserole',),
        ),
        migrations.CreateModel(
            name='Moderator',
            fields=[
                ('baserole_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='roles.baserole')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('roles.baserole',),
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('baserole_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='roles.baserole')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('roles.baserole',),
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('baserole_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='roles.baserole')),
                ('political_list', models.CharField(max_length=16, verbose_name='Political list')),
                ('political_role', models.CharField(max_length=16, verbose_name='Political role')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('roles.baserole',),
        ),
        migrations.CreateModel(
            name='SuperAdministrator',
            fields=[
                ('baserole_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='roles.baserole')),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('roles.baserole',),
        ),
    ]
