# Generated by Django 3.2.9 on 2022-04-03 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baserole',
            name='extra_groups',
            field=models.BooleanField(default=False, help_text='Groups without an associated degree', verbose_name='Extra groups'),
        ),
    ]
