# Generated by Django 3.2.9 on 2022-04-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_baserole_extra_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='baserole',
            name='custom_title_override',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Custom title'),
        ),
    ]
