# Generated by Django 3.2.5 on 2021-07-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.ManyToManyField(related_name='courses', through='university.CourseDegree', to='university.Degree'),
        ),
    ]
