# Generated by Django 3.2.5 on 2021-07-27 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_course_degree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='degree',
            new_name='degrees',
        ),
    ]
