# Generated by Django 3.2.5 on 2021-08-03 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_rename_degree_course_degrees'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='slug',
            field=models.CharField(default='default_slug', max_length=64, verbose_name='slug'),
        ),
    ]
