# Generated by Django 3.2.6 on 2021-08-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0006_representative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='name'),
        ),
        migrations.AlterUniqueTogether(
            name='degree',
            unique_together={('name', 'type')},
        ),
    ]
