# Generated by Django 3.2.5 on 2021-08-31 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0009_auto_20210829_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='representative',
            old_name='title',
            new_name='degree_name',
        ),
    ]
