# Generated by Django 3.2.6 on 2021-09-04 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0010_auto_20210831_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='degree_name',
            field=models.CharField(max_length=64, verbose_name='degree name'),
        ),
    ]
