# Generated by Django 3.2.9 on 2023-08-15 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('university', '0013_featuredgroup'), ('university', '0014_auto_20230815_1957')]

    dependencies = [
        ('telegrambot', '__first__'),
        ('university', '0012_auto_20220911_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Display name')),
                ('description', models.CharField(max_length=150, verbose_name='Display description')),
                ('category', models.CharField(blank=True, choices=[('u', 'University group'), ('a', 'Announcement group'), ('s', 'Student association group')], max_length=2, null=True, verbose_name='Extra group category')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='Image URL')),
                ('external_url', models.URLField(blank=True, null=True, verbose_name='External URL')),
                ('button_name', models.CharField(blank=True, max_length=16, null=True, verbose_name='Button name')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegrambot.group')),
                ('description_en', models.CharField(max_length=150, null=True, verbose_name='Display description')),
                ('description_it', models.CharField(max_length=150, null=True, verbose_name='Display description')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='Display name')),
                ('name_it', models.CharField(max_length=150, null=True, verbose_name='Display name')),
                ('button_name_en', models.CharField(blank=True, max_length=16, null=True, verbose_name='Button name')),
                ('button_name_it', models.CharField(blank=True, max_length=16, null=True, verbose_name='Button name')),
            ],
            options={
                'verbose_name': 'Featured Group',
                'verbose_name_plural': 'Featured Groups',
            },
        ),
    ]
